### ISSUE TITLE
Should the mailer support translating subjects when provided with zope.i18nmessageid.message.Message?

### ISSUE THREAD

**Issue by cutz** [NextThought/nti.mailer#18]
One of our applications is providing zope.i18nmessageid.message.Message objects for the subject argument of `queue_simple_html_text_email`. A [recent change](https://github.com/NextThought/nti.dataserver/pull/491) to that application made it evident that this argument is not being translated (mapping parameters aren't being mapped). Should this library support translations for fields like subject, or should we translate before calling `queue_simple_html_text_email`?

**Comment by jamadden** [comment]
0.0.1a2 with this is now on PyPI. (0.0.1a1 in PyPI is the previous version of the code before #21 and #25).
